

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: npm install
  displayName: 'Run a one-line script'

- script: |
    
    npm run build
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Run a multi-line script'
